[server]
bind_addr = "0.0.0.0:2333" # The port the client connects to
default_token = "private_secure_token"

[server.services.http]
type = "tcp"
bind_addr = "0.0.0.0:80"

[server.services.https]
type = "tcp"
bind_addr = "0.0.0.0:443"

[server.services.cs_game]
type = "udp"
bind_addr = "0.0.0.0:27015"

[server.services.cs_rcon]
type = "tcp"
bind_addr = "0.0.0.0:28015"