apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loki-pvc
spec:
  storageClassName: dellcsi-powerstore-nfs-test
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi # Adjust size based on your retention needs
