services:
    postgres:
        image: postgres:18-alpine
        container_name: postgres
        restart: always

        environment:
            TZ: Asia/Ulaanbaatar
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: supersecret
            POSTGRES_DB: postgres

        volumes:
            - postgres_data:/var/lib/postgresql
            - ./init-multiple-databases.sh:/docker-entrypoint-initdb.d/init-multiple-databases.sh:ro

        ports:
            - "5432:5432"

        command:
            - "postgres"
            - "-c"
            - "password_encryption=scram-sha-256"
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U admin -d postgres"]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 10s

        networks:
            - backend_network

    keycloak:
        image: quay.io/keycloak/keycloak:26.6.1
        container_name: keycloak
        restart: always
        command: start-dev
        ports:
            - "8080:8080"
        environment:
            KC_HOSTNAME: http://sso.local:8080
            KC_HOSTNAME_STRICT: "false"
            KC_HOSTNAME_STRICT_BACKCHANNEL: "false"
            KC_PROXY_HEADERS: xforwarded
            KC_BOOTSTRAP_ADMIN_USERNAME: "admin"
            KC_BOOTSTRAP_ADMIN_PASSWORD: "admin"
            KC_DB: "postgres"
            KC_DB_URL_HOST: "postgres"
            KC_DB_USERNAME: "admin"
            KC_DB_PASSWORD: "supersecret"
            KC_DB_TLS_MODE: "disabled"
            TZ: "Asia/Ulaanbaatar"
        depends_on:
            - postgres
        networks:
            - backend_network

    forgejo:
        image: codeberg.org/forgejo/forgejo:15
        container_name: forgejo
        environment:
            TZ: Asia/Ulaanbaatar
            USER_UID: 1000
            USER_GID: 1000
            FORGEJO__database__DB_TYPE: "postgres"
            FORGEJO__database__HOST: "postgres:5432"
            FORGEJO__database__NAME: forgejo
            FORGEJO__database__USER: admin
            FORGEJO__database__PASSWD: supersecret
            # FORGEJO__service__DISABLE_REGISTRATION: "true"
            # FORGEJO__auth__DISABLE_LOCAL_AUTHENTICATION: "true"
            FORGEJO__service__SHOW_REGISTRATION_BUTTON: "false"
            FORGEJO__oauth2_client__ENABLE_AUTO_REGISTRATION: "true"
            FORGEJO__oauth2_client__ACCOUNT_LINKING: "auto"
        restart: always
        extra_hosts:
            sso.local: host-gateway
        networks:
            - backend_network
        depends_on:
            - keycloak
        volumes:
            - forgejo_data:/data
            # - ./app.ini:/etc/forgejo
        ports:
            - "3000:3000"
            - "222:22"

    # dind:
    #     image: docker:27-dind
    #     container_name: forgejo-dind
    #     privileged: true
    #     environment:
    #     DOCKER_TLS_CERTDIR: /certs
    #     volumes:
    #         - forgejo-dind-certs:/certs
    #         - forgejo-dind-data:/var/lib/docker
    #     networks:
    #         - backend_network

    # runner:
    #     image: codeberg.org/forgejo/runner:6.2.2
    #     container_name: forgejo-runner
    #     restart: always
    #     depends_on:
    #         - forgejo
    #         - dind
    #     environment:
    #         # Use the internal service name and port
    #         FORGEJO_INSTANCE_URL: http://forgejo:3000
    #         # PASTE YOUR TOKEN HERE
    #         FORGEJO_RUNNER_REGISTRATION_TOKEN: "bcd64bc1f35160d9490129f37f4133cbef63b103"
    #         FORGEJO_RUNNER_NAME: "devsecops-runner"
    #         # This sets your specific label
    #         FORGEJO_RUNNER_LABELS: "4433:docker://node:20-bookworm"
    #         DOCKER_HOST: tcp://dind:2376
    #         DOCKER_CERT_PATH: /certs/client
    #         DOCKER_TLS_VERIFY: 1
    #     volumes:
    #         - forgejo-runner-data:/data
    #         - forgejo-dind-certs:/certs/client:ro
    #     networks:
    #         - backend_network

volumes:
    postgres_data:
        driver: local
    forgejo_data:
        driver: local
    # forgejo-dind-certs:
    #     driver: local
    # forgejo-dind-data:
    #     driver: local
    # forgejo-runner-data:
    #     driver: local

networks:
    backend_network:
        external: false
