apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: forgejo-data-pvc
spec:
    accessModes: ["ReadWriteMany"]
    storageClassName: your-nfs-storage-class
    resources:
        requests:
            storage: 5Gi
