stages:
  - upload

upload:
  stage: upload
  image: registry-gitlab.hello.com/devops/container-images/k8s:1.30.6
  variables:
    HELM_NAME: $CI_PROJECT_NAME
    HELM_TAG: $CI_COMMIT_TAG
  before_script:
    - helm package . --version=$HELM_TAG
  script:
    - 'curl -k --fail-with-body --request POST --user gitlab-ci-token:$CI_JOB_TOKEN --form "chart=@${HELM_NAME}-${HELM_TAG}.tgz" "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/helm/api/stable/charts"'
  rules:
    - if: $CI_COMMIT_TAG
