apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: single-replica-db
  namespace: cnpg-system
spec:
  instances: 1
  storage:
    size: 1Gi
  managed:
    roles:
      - name: keycloak_test
        ensure: present
        login: true
        passwordSecret: # name of the secret
          name: keycloak-test-user
      - name: gitlab
        ensure: present
        login: true
        passwordSecret: 
          name: gitlab-user # name of the secret (kubectl get secrets | grep gitlab)
      # - name: onedev_test
      #   ensure: present
      #   login: true
      #   passwordSecret: # name of the secret
      #     name: onedev-test-user
      